Header H
int16  mpuData_AcX
int16  mpuData_AcY
int16  mpuData_AcZ
uint32  mpuData_timestamp
int16  mpuData_Tmp
int16  mpuData_GyX
int16  mpuData_GyY
int16  mpuData_GyZ

int16  mpuRAW_AcX
int16  mpuRAW_AcY
int16  mpuRAW_AcZ
uint32  mpuRAW_timestamp
int16  mpuRAW_Tmp
int16  mpuRAW_GyX
int16  mpuRAW_GyY
int16  mpuRAW_GyZ

float32  pingheight

uint32  ppfb_timestamp
float64  ppfb_Input
float64  ppfb_Kd
float64  ppfb_Ki
float64  ppfb_Kp
float64  ppfb_Output
float64  ppfb_Setpoint

uint32  pplr_timestamp
float64  pplr_Input
float64  pplr_Kd
float64  pplr_Ki
float64  pplr_Kp
float64  pplr_Output
float64  pplr_Setpoint

uint32  ppud_timestamp
float64  ppud_Input
float64  ppud_Kd
float64  ppud_Ki
float64  ppud_Kp
float64  ppud_Output
float64  ppud_Setpoint

float32  yaw
float32  pitch
float32  roll

uint32  timestamp
uint16  tune_type
