# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from atom_esp_joy/joydata.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class joydata(genpy.Message):
  _md5sum = "9ea973d7e29e9a09bf4c38bea786a98f"
  _type = "atom_esp_joy/joydata"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 X
int16 Y
int16 Z
int16 S
uint16 buttons # F1,B2,3,4,5,6,7,8,9,10,11,12,H1,2,3,4
# 0000 0
# 0001 1
# 0010 2
# 0011 3
# 0100 4
# 0101 5
# 0110 6
# 0111 7
# 1000 8
"""
  __slots__ = ['X','Y','Z','S','buttons']
  _slot_types = ['int16','int16','int16','int16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       X,Y,Z,S,buttons

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(joydata, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.X is None:
        self.X = 0
      if self.Y is None:
        self.Y = 0
      if self.Z is None:
        self.Z = 0
      if self.S is None:
        self.S = 0
      if self.buttons is None:
        self.buttons = 0
    else:
      self.X = 0
      self.Y = 0
      self.Z = 0
      self.S = 0
      self.buttons = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4hH().pack(_x.X, _x.Y, _x.Z, _x.S, _x.buttons))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.X, _x.Y, _x.Z, _x.S, _x.buttons,) = _get_struct_4hH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4hH().pack(_x.X, _x.Y, _x.Z, _x.S, _x.buttons))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.X, _x.Y, _x.Z, _x.S, _x.buttons,) = _get_struct_4hH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4hH = None
def _get_struct_4hH():
    global _struct_4hH
    if _struct_4hH is None:
        _struct_4hH = struct.Struct("<4hH")
    return _struct_4hH
