.PHONY: clean All

All:
	@echo "----------Building project:[ test_NN_1 - Debug ]----------"
	@cd "test_NN_1" && "$(MAKE)" -f  "test_NN_1.mk"
clean:
	@echo "----------Cleaning project:[ test_NN_1 - Debug ]----------"
	@cd "test_NN_1" && "$(MAKE)" -f  "test_NN_1.mk" clean
