// Generated by gencpp from file atom_esp_listener/PID_Tune_Params.msg
// DO NOT EDIT!


#ifndef ATOM_ESP_LISTENER_MESSAGE_PID_TUNE_PARAMS_H
#define ATOM_ESP_LISTENER_MESSAGE_PID_TUNE_PARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace atom_esp_listener
{
template <class ContainerAllocator>
struct PID_Tune_Params_
{
  typedef PID_Tune_Params_<ContainerAllocator> Type;

  PID_Tune_Params_()
    : header()
    , timestamp(0)
    , Setpoint(0.0)
    , Input(0.0)
    , Output(0.0)
    , Kd(0.0)
    , Ki(0.0)
    , Kp(0.0)  {
    }
  PID_Tune_Params_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0)
    , Setpoint(0.0)
    , Input(0.0)
    , Output(0.0)
    , Kd(0.0)
    , Ki(0.0)
    , Kp(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _timestamp_type;
  _timestamp_type timestamp;

   typedef double _Setpoint_type;
  _Setpoint_type Setpoint;

   typedef double _Input_type;
  _Input_type Input;

   typedef double _Output_type;
  _Output_type Output;

   typedef double _Kd_type;
  _Kd_type Kd;

   typedef double _Ki_type;
  _Ki_type Ki;

   typedef double _Kp_type;
  _Kp_type Kp;




  typedef boost::shared_ptr< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> const> ConstPtr;

}; // struct PID_Tune_Params_

typedef ::atom_esp_listener::PID_Tune_Params_<std::allocator<void> > PID_Tune_Params;

typedef boost::shared_ptr< ::atom_esp_listener::PID_Tune_Params > PID_Tune_ParamsPtr;
typedef boost::shared_ptr< ::atom_esp_listener::PID_Tune_Params const> PID_Tune_ParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace atom_esp_listener

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'atom_esp_listener': ['/home/rahuldeo/ATOM/ATOM_DRONE/ros/rosatom/src/atom_esp_listener/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7b9a3a1c6b3d0aceef163325064bf57";
  }

  static const char* value(const ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7b9a3a1c6b3d0acULL;
  static const uint64_t static_value2 = 0xeef163325064bf57ULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_esp_listener/PID_Tune_Params";
  }

  static const char* value(const ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32  timestamp\n\
float64 Setpoint\n\
float64 Input\n\
float64 Output\n\
float64 Kd\n\
float64 Ki\n\
float64 Kp\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.Setpoint);
      stream.next(m.Input);
      stream.next(m.Output);
      stream.next(m.Kd);
      stream.next(m.Ki);
      stream.next(m.Kp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PID_Tune_Params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atom_esp_listener::PID_Tune_Params_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "Setpoint: ";
    Printer<double>::stream(s, indent + "  ", v.Setpoint);
    s << indent << "Input: ";
    Printer<double>::stream(s, indent + "  ", v.Input);
    s << indent << "Output: ";
    Printer<double>::stream(s, indent + "  ", v.Output);
    s << indent << "Kd: ";
    Printer<double>::stream(s, indent + "  ", v.Kd);
    s << indent << "Ki: ";
    Printer<double>::stream(s, indent + "  ", v.Ki);
    s << indent << "Kp: ";
    Printer<double>::stream(s, indent + "  ", v.Kp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_ESP_LISTENER_MESSAGE_PID_TUNE_PARAMS_H
