// Generated by gencpp from file atom_esp_listener/Profiler_data.msg
// DO NOT EDIT!


#ifndef ATOM_ESP_LISTENER_MESSAGE_PROFILER_DATA_H
#define ATOM_ESP_LISTENER_MESSAGE_PROFILER_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace atom_esp_listener
{
template <class ContainerAllocator>
struct Profiler_data_
{
  typedef Profiler_data_<ContainerAllocator> Type;

  Profiler_data_()
    : header()
    , timestamp(0)
    , averageIterationCount(0)
    , averageTime(0.0)
    , averageTime2(0.0)
    , averageTick(0)  {
    }
  Profiler_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0)
    , averageIterationCount(0)
    , averageTime(0.0)
    , averageTime2(0.0)
    , averageTick(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint16_t _averageIterationCount_type;
  _averageIterationCount_type averageIterationCount;

   typedef float _averageTime_type;
  _averageTime_type averageTime;

   typedef float _averageTime2_type;
  _averageTime2_type averageTime2;

   typedef uint32_t _averageTick_type;
  _averageTick_type averageTick;




  typedef boost::shared_ptr< ::atom_esp_listener::Profiler_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_esp_listener::Profiler_data_<ContainerAllocator> const> ConstPtr;

}; // struct Profiler_data_

typedef ::atom_esp_listener::Profiler_data_<std::allocator<void> > Profiler_data;

typedef boost::shared_ptr< ::atom_esp_listener::Profiler_data > Profiler_dataPtr;
typedef boost::shared_ptr< ::atom_esp_listener::Profiler_data const> Profiler_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_esp_listener::Profiler_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace atom_esp_listener

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'atom_esp_listener': ['/home/rahuldeo/ATOM/ATOM_DRONE/ros/rosatom/src/atom_esp_listener/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_esp_listener::Profiler_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_esp_listener::Profiler_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_esp_listener::Profiler_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c31fa7394a8f9d53d1de6f6692e65a32";
  }

  static const char* value(const ::atom_esp_listener::Profiler_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc31fa7394a8f9d53ULL;
  static const uint64_t static_value2 = 0xd1de6f6692e65a32ULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_esp_listener/Profiler_data";
  }

  static const char* value(const ::atom_esp_listener::Profiler_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n\
uint32  timestamp\n\
uint16  averageIterationCount\n\
float32 averageTime # micros\n\
float32 averageTime2 # micros\n\
uint32  averageTick\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::atom_esp_listener::Profiler_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.averageIterationCount);
      stream.next(m.averageTime);
      stream.next(m.averageTime2);
      stream.next(m.averageTick);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Profiler_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_esp_listener::Profiler_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atom_esp_listener::Profiler_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "averageIterationCount: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.averageIterationCount);
    s << indent << "averageTime: ";
    Printer<float>::stream(s, indent + "  ", v.averageTime);
    s << indent << "averageTime2: ";
    Printer<float>::stream(s, indent + "  ", v.averageTime2);
    s << indent << "averageTick: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.averageTick);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_ESP_LISTENER_MESSAGE_PROFILER_DATA_H
